# This file contains all user-specific information
# Example:
#  host: "example.okera.com"
#  token: "okera acces token"
#  collibra_dgc: "https://example.collibra.com:443"
#  collibra_username: "username"
#  collibra_password: "password"
#  community: "Example Community"
#  domain: 
#      name: "Example Domain"
#      type: "Data Asset Domain" 
#  #  mapped_attribute_okera_namespaces:
#    - {attribute_name: "Information Classification", attribute_id: "123-abc-123abc-123", okera_namespace: "information_classification"}
#    - {attribute_name: "Custom Attribute 2", attribute_id: "456-def-456def-456", okera_namespace: "attribute_2"}
#  full_name_prefixes:
#    - "Prefix One"
#    - "Prefix Two"
#
configs:
  host: "sandbox.demo.okera.com"
  token: "AAtsYXVyYV9hZG1pbgALbGF1cmFfYWRtaW6KAXFe0V9-igFxgt3jfggZ.dFtjz244QiYsJCMqD9AEUVAw7dk$"
  collibra_dgc: "https://okera.collibra.com:443"
  collibra_username: "Admin"
  collibra_password: "Gac2Quencotdilo"
  community: "Okera3.0"
  domain: 
    name: "export_only"
    type: "Physical Data Dictionary" 
  #
  # Collibra custom attribute mapping information. 
  # Specify what Collibra custom attribute you would like mapped to an Okera tag namespace.
  # If the Okera tag namespace already exists, the values of the Collibra attribute 
  # will be added there as Okera tags. If it doesn't, a new namespace will be created
  # in Okera with the name provided.
  #
  mapped_attribute_okera_namespaces:
    #- {attribute_name: "Information Classification", attribute_id: "339481cfd-bace-4634-9277-ceacb9b71e87", okera_namespace: "information_classification"}
    #- {attribute_name: "PII 2", attribute_id: "48007d3a-7843-45e0-a99b-5117fa16576f", okera_namespace: "pii_2"}
  full_name_prefixes:
   # - "Trusted Zone"
    #- "Raw Zone"
