# This file contains all user-specific information
# Example:
#  host: "example.okera.com"
#  token: "okera acces token"
#  collibra_dgc: "https://example.collibra.com:443"
#  collibra_username: "username"
#  collibra_password: "password"
#  community: "Example Community"
#  domain: 
#      name: "Example Domain"
#      type: "Data Asset Domain" 
#  info_classif_namespace: "information_classification"

configs:
  host: "sandbox.demo.okera.com"
  token: "AAtsYXVyYV9hZG1pbgALbGF1cmFfYWRtaW6KAXFUfHSVigFxeIj4lQYV.BHlJpMDpmWSizDETN0vfAtPpdrA$"
  collibra_dgc: "https://okera.collibra.com:443"
  collibra_username: "Admin"
  collibra_password: "Gac2Quencotdilo"
  community: "Okera3.0"
  domain: 
      name: "import"
      type: "Physical Data Dictionary" 
  #
  # Collibra custom attribute mapping information. 
  # Specify what Collibra custom attribute you would like mapped to an Okera tag namespace.
  # If the Okera tag namespace already exists, the values of the Collibra attribute 
  # will be added there as Okera tags. If it doesn't, a new namespace will be created
  # in Okera with the name provided.
  #
  mapped_attribute_okera_namespace: "information_classification"