# This file contains all user-specific information
# Example:
#  host: "example.okera.com"
#  token: "okera acces token"
#  collibra_dgc: "https://example.collibra.com:443"
#  collibra_username: "username"
#  collibra_password: "password"
#  community: "Example Community"
#  domain:
#      name: "Example Domain"
#      type: "Data Asset Domain"
#  info_classif_namespace: "information_classification"
configs:
  log_directory: "logs"
  okera_host: "aws21.demo.okera.com"
  okera_token:
  collibra_dgc: "https://okera.collibra.com:443"
  collibra_username: "Admin"
  collibra_password: "Gac2Quencotdilo"
  collibra_assets: "assets.yaml"
  community:
  domain:
      name:
      type: